[metadata]
name = "Lone Sailor"
author = "Sherman Rofeman"
origin_url = "https://github.com/skippyr/lone-sailor"
[colors]
background = "#140b0c"
foreground = "#bbaa88"
cursor_bg = "#bbaa88"
cursor_fg = "#140b0c"
selection_bg = "#bbaa88"
selection_fg = "#140b0c"
ansi = [
	"#140b0c",
	"#99270b",
	"#8a7065",
	"#8a5942",
	"#686b73",
	"#733e45",
	"#665944",
	"#bbaa88"
]
brights = [
	"#686b73",
	"#99270b",
	"#8a7065",
	"#8a5942",
	"#686b73",
	"#733e45",
	"#665944",
	"#bbaa88"
]
